name: life-sciences-a11y-evaluation
channels:
  - conda-forge
dependencies:
  - python==3.10.*
  - numpy
  - pandas
  - jupyterlab
  - ipykernel
  - altair==5.1.*
  - altair_saver==0.5.*
  - pip:
    - axe-playwright-python==0.1.4
    - playwright
